import { chromium } from '@playwright/test';
import { mkdirSync } from 'node:fs';
mkdirSync('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');
await page.getByRole('button',{name:'Explore the interactive demo'}).click();
await page.getByRole('heading',{name:'A little closer, every day.'}).waitFor();
await page.screenshot({path:'artifacts/dashboard-desktop.png',fullPage:true});
await page.getByRole('button',{name:'New conversation',exact:true}).click();
await page.getByLabel('Give your conversation a title').fill('A browser-tested conversation');
await page.getByLabel('A little context').fill('Let’s find a calm time to talk together.');
await page.getByRole('button',{name:'Share with my partner'}).click();
await page.getByRole('button',{name:/A browser-tested conversation/}).click();
await page.getByText('Your partner will choose a weekend date and time.').waitFor();
if(await page.getByRole('button',{name:'Set our conversation time'}).count())throw Error('Creator sees scheduling action');
await page.getByRole('button',{name:'Close dialog'}).click();
await page.getByRole('button',{name:/A calmer morning routine/}).click();
await page.getByRole('button',{name:'Set our conversation time'}).click();
await page.getByRole('button',{name:'Our calendar',exact:true}).click();
await page.getByRole('button',{name:/A calmer morning routine/}).waitFor();
await page.getByRole('button',{name:'Couple goals',exact:true}).click();
await page.getByRole('button',{name:'Add a goal'}).click();
await page.getByLabel('Our goal',{exact:true}).fill('Walk together');
await page.getByLabel('Target',{exact:true}).fill('10');
await page.getByRole('button',{name:'Create our goal'}).click();
await page.getByRole('heading',{name:'Walk together'}).waitFor();
await page.getByRole('button',{name:'Our money',exact:true}).click();
await page.getByLabel('Your take-home income').fill('50000');
await page.getByRole('button',{name:'Save monthly plan'}).click();
await page.getByText('₹90,000',{exact:true}).waitFor();
await page.getByRole('button',{name:'Overview',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.emulateMedia({reducedMotion:'reduce'});
await page.getByRole('status').waitFor({state:'hidden'});
await page.screenshot({path:'artifacts/dashboard-mobile.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
if(overflow)throw Error('Mobile horizontal overflow');
await page.getByRole('button',{name:'Open navigation'}).click();
await page.getByRole('button',{name:'Our agreements',exact:true}).click();
await page.getByRole('heading',{name:'The way we care for us.'}).waitFor();
if(errors.length)throw Error(errors.join('\n'));
console.log('PASS: demo topic ownership, scheduling, goals, monthly income, mobile navigation, no overflow or page errors');
await browser.close();
