import test from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from './app.js';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

test('private household integration, scheduling, finance, and persistent notifications',async t=>{
 const directory=mkdtempSync(join(tmpdir(),'together-test-')),database=join(directory,'test.sqlite');
 let service=createApp({database,env:{SETUP_CODE:'private-test-code'}});
 const server=service.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 t.after(async()=>{await new Promise(r=>server.close(r));service.close();rmSync(directory,{recursive:true,force:true});});
 const url=`http://127.0.0.1:${server.address().port}`;
 async function call(path,method='GET',body,cookie,headers={}) {const res=await fetch(url+'/api'+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{}),...headers},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};}
 const registration={name:'A',email:'a@example.com',password:'a-secure-password',whatsapp:'+919000000001'};
 assert.equal((await call('/state')).status,401);
 assert.equal((await call('/register','POST',registration)).status,403);
 assert.equal((await call('/register','POST',{...registration,whatsapp:'',inviteCode:'private-test-code'})).status,400);
 assert.equal((await call('/register','POST',{...registration,whatsapp:'919876543210',inviteCode:'private-test-code'})).status,400);
 assert.equal((await call('/register','POST',{...registration,password:'12345678901',inviteCode:'private-test-code'})).status,400);
 const a=await call('/register','POST',{...registration,inviteCode:'private-test-code'});assert.equal(a.status,201);
 assert.ok(a.cookie);
 const initialAgreements=(await call('/state','GET',undefined,a.cookie)).data.agreements;
 assert.equal(initialAgreements.length,5);assert.ok(initialAgreements.every(a=>a.acceptedBy.length===0));
 const invite=await call('/invite','GET',undefined,a.cookie);
 const b=await call('/register','POST',{...registration,name:'B',email:'b@example.com',inviteCode:invite.data.inviteCode});assert.equal(b.status,201);
 assert.equal((await call('/state','GET',undefined,b.cookie)).data.agreements.length,5);
 assert.equal((await call('/register','POST',{...registration,email:'c@example.com',inviteCode:invite.data.inviteCode})).status,403);
 assert.equal((await call('/login','POST',{email:registration.email,password:'wrong'})).status,401);
 assert.equal((await call('/login','POST',{email:registration.email,password:registration.password})).status,200);
 assert.equal((await call('/topics','POST',{title:'X',category:'Life'},a.cookie,{Origin:'https://evil.example'})).status,403);
 const draft=await call('/topics','POST',{title:'Private',description:'Secret',category:'Life',draft:true},a.cookie);
 assert.equal((await call('/state','GET',undefined,b.cookie)).data.topics.length,0);
 assert.equal((await call('/topics/'+draft.data.id,'PATCH',{action:'edit',title:'Intrusion'},b.cookie)).status,404);
 const refined=await call('/topics/'+draft.data.id,'PATCH',{action:'edit',title:'Refined privately',description:'A clearer thought',category:'Connection'},a.cookie);
 assert.equal(refined.status,200);assert.equal(refined.data.title,'Refined privately');assert.equal(refined.data.description,'A clearer thought');assert.equal(refined.data.category,'Connection');
 assert.equal((await call('/state','GET',undefined,b.cookie)).data.notifications.length,0);
 assert.equal((await call('/topics/'+draft.data.id,'PATCH',{action:'publish'},b.cookie)).status,404);
 assert.equal((await call('/topics/'+draft.data.id,'PATCH',{action:'publish'},a.cookie)).status,200);
 assert.equal((await call('/topics/'+draft.data.id,'PATCH',{action:'edit',title:'Too late'},a.cookie)).status,403);
 const recipientNotices=(await call('/state','GET',undefined,b.cookie)).data.notifications;
 assert.equal(recipientNotices.filter(n=>n.type==='topic').length,1);
 assert.equal((await call('/state','GET',undefined,a.cookie)).data.notifications.filter(n=>n.type==='topic').length,0);
 const date=new Date(Date.now()+86400000*7);while(date.getUTCDay()!==6)date.setUTCDate(date.getUTCDate()+1);const saturday=date.toISOString().slice(0,10);
 const schedule={action:'schedule',date:saturday,time:'12:00',duration:30};
 assert.equal((await call('/topics/'+draft.data.id,'PATCH',schedule,a.cookie)).status,403);
 assert.equal((await call('/topics/'+draft.data.id,'PATCH',{...schedule,date:'2030-01-07'},b.cookie)).status,400);
 assert.equal((await call('/topics/'+draft.data.id,'PATCH',schedule,b.cookie)).status,200);
 assert.equal((await call('/state','GET',undefined,a.cookie)).data.notifications.filter(n=>n.type==='schedule').length,1);
 assert.equal((await call('/state','GET',undefined,b.cookie)).data.notifications.filter(n=>n.type==='schedule').length,0);
 const reminderTime=new Date(Date.parse(`${saturday}T12:00:00+05:30`)-3500000);
 await service.runWorker(reminderTime);await service.runWorker(reminderTime);
 for(const cookie of [a.cookie,b.cookie])assert.equal((await call('/state','GET',undefined,cookie)).data.notifications.filter(n=>n.type==='discussion_reminder').length,1);
 const other=await call('/topics','POST',{title:'Other',category:'Life'},a.cookie);
 assert.equal((await call('/topics/'+other.data.id,'PATCH',schedule,b.cookie)).status,400);
 const finance={month:'2030-01',revision:0,income:1000,expenses:400,savings:200,accounts:[{id:'savings',name:'Shared',last4:'1234',purpose:'Savings'}],transfers:['savings']};
 assert.equal((await call('/finance','PUT',finance,a.cookie)).status,200);
 assert.equal((await call('/finance','PUT',{...finance,accounts:[...finance.accounts,{id:'another',name:'Other',last4:'5678',purpose:'Savings'}]},a.cookie)).status,400);
 assert.equal((await call('/finance','PUT',{...finance,income:2000,expenses:999},b.cookie)).status,409);
 const current=(await call('/state?month=2030-01','GET',undefined,b.cookie)).data.finance;
 assert.equal(current.revision,1);assert.equal(current.expenses,400);
 assert.equal((await call('/finance','PUT',{...current,income:2000},b.cookie)).status,200);
 const state=(await call('/state?month=2030-01','GET',undefined,a.cookie)).data;
 assert.equal(state.finance.incomes[a.data.user.id],1000);assert.equal(state.finance.incomes[b.data.user.id],2000);
 assert.equal(state.finance.revision,2);assert.equal(state.finance.expenses,400);
 assert.equal((await call('/state?month=2030-02','GET',undefined,a.cookie)).data.finance.expenses,0);
 await service.runWorker(new Date('2030-01-07T04:00:00Z'));await service.runWorker(new Date('2030-01-07T04:01:00Z'));
 const notices=(await call('/state','GET',undefined,a.cookie)).data.notifications;
 assert.equal(notices.filter(n=>n.type==='monthly').length,1);
 assert.ok(notices.every(n=>n.delivery.every(d=>d.status==='not_configured')));
 const extra=createApp({database,env:{SETUP_CODE:'private-test-code'}});assert.ok(extra.db.prepare("SELECT count(*) AS n FROM records WHERE kind='topics'").get().n===2);extra.close();
 assert.equal((await call('/logout','POST',{},a.cookie)).status,200);assert.equal((await call('/state','GET',undefined,a.cookie)).status,401);
});

test('OpenWA adapter retries failures with bounded attempts and generic content',async t=>{
 const requests=[];
 const service=createApp({database:':memory:',env:{OPENWA_BASE_URL:'https://provider.invalid',OPENWA_API_KEY:'test-key',OPENWA_SESSION_ID:'session'},fetch:async(url,options)=>{requests.push({url,options});return {ok:false};}});
 t.after(()=>service.close());
 const put=(kind,obj)=>service.db.prepare('INSERT INTO records VALUES (?,?,?)').run(kind,obj.id,JSON.stringify(obj));
 put('users',{id:'user',name:'A',email:'a@example.com',whatsapp:'+919876543210'});
 put('notifications',{id:'notice',userId:'user',title:'Your partner has shared a new topic. Open Together to read it.'});
 put('outbox',{id:'out',userId:'user',notificationId:'notice',channel:'whatsapp',status:'pending',attempts:0,nextAttempt:0});
 for(let i=0;i<6;i++)await service.runWorker(new Date(Date.now()+i*7200000));
 assert.equal(requests.length,4);
 assert.equal(requests[0].url,'https://provider.invalid/api/sessions/session/messages/send-text');
 assert.equal(requests[0].options.headers['X-API-Key'],'test-key');
 assert.equal(JSON.parse(requests[0].options.body).chatId,'919876543210@c.us');
 assert.equal(JSON.parse(service.db.prepare("SELECT data FROM records WHERE kind='outbox' AND id='out'").get().data).status,'failed');
});

test('Evolution API is preferred and sends generic WhatsApp text',async t=>{
 const requests=[];
 const service=createApp({database:':memory:',env:{EVOLUTION_API_URL:'https://evolution.invalid',EVOLUTION_API_KEY:'evo-key',EVOLUTION_INSTANCE:'hearth',OPENWA_BASE_URL:'https://openwa.invalid',OPENWA_API_KEY:'ignored',OPENWA_SESSION_ID:'ignored'},fetch:async(url,options)=>{requests.push({url,options});return {ok:true};}});
 t.after(()=>service.close());
 const put=(kind,obj)=>service.db.prepare('INSERT INTO records VALUES (?,?,?)').run(kind,obj.id,JSON.stringify(obj));
 put('users',{id:'user',name:'A',email:'a@example.com',whatsapp:'+91 98765 43210'});
 put('notifications',{id:'notice',userId:'user',title:'Your partner has shared a new topic. Open Together to read it.'});
 put('outbox',{id:'out',userId:'user',notificationId:'notice',channel:'whatsapp',status:'pending',attempts:0,nextAttempt:0});
 await service.runWorker();
 assert.equal(requests.length,1);
 assert.equal(requests[0].url,'https://evolution.invalid/message/sendText/hearth');
 assert.equal(requests[0].options.headers.apikey,'evo-key');
 const body=JSON.parse(requests[0].options.body);
 assert.equal(body.number,'919876543210');
 assert.equal(body.text,'Your partner has shared a new topic. Open Together to read it.');
 assert.equal(JSON.parse(service.db.prepare("SELECT data FROM records WHERE kind='outbox' AND id='out'").get().data).status,'accepted');
});

test('OpenWA successful response records acceptance without claiming receipt',async t=>{
 let calls=0;
 const service=createApp({database:':memory:',env:{OPENWA_BASE_URL:'https://provider.invalid',OPENWA_API_KEY:'test-key',OPENWA_SESSION_ID:'session'},fetch:async()=>{calls++;return {ok:true};}});
 t.after(()=>service.close());
 const put=(kind,obj)=>service.db.prepare('INSERT INTO records VALUES (?,?,?)').run(kind,obj.id,JSON.stringify(obj));
 put('users',{id:'user',name:'A',email:'a@example.com',whatsapp:'+919876543210'});
 put('notifications',{id:'notice',userId:'user',title:'Your partner has shared a new topic. Open Together to read it.'});
 put('outbox',{id:'out',userId:'user',notificationId:'notice',channel:'whatsapp',status:'pending',attempts:0,nextAttempt:0});
 await service.runWorker();await service.runWorker();
 assert.equal(calls,1);
 const out=JSON.parse(service.db.prepare("SELECT data FROM records WHERE kind='outbox' AND id='out'").get().data);
 assert.equal(out.status,'accepted');assert.ok(out.acceptedAt);assert.equal(out.sentAt,undefined);
});

