import {readFile,writeFile,rename} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomBytes} from 'node:crypto';
import {z} from 'zod';
import nodemailer from 'nodemailer';

let writeQueue=Promise.resolve();
export function saveEnvPatch(patch,path=resolve('.env')){
 const run=async()=>{let content='';try{content=await readFile(path,'utf8')}catch(e){if(e.code!=='ENOENT')throw e}
 const keys=new Set(Object.keys(patch));const lines=content.split(/\r?\n/).filter(line=>!keys.has(line.match(/^\s*([A-Z_]+)\s*=/)?.[1]));
 for(const [key,value]of Object.entries(patch)){if(!/^[A-Z_]+$/.test(key)||/[\r\n\0]/.test(String(value)))throw Error('Invalid configuration');const raw=String(value);if(raw.includes("'"))throw Error('Configuration values cannot contain a single quote.');lines.push(`${key}='${raw}'`)}
 const temp=path+'.'+randomBytes(6).toString('hex')+'.tmp';await writeFile(temp,lines.join('\n')+'\n',{mode:0o600});await rename(temp,path);
 };const next=writeQueue.then(run);writeQueue=next.catch(()=>{});return next;
}
const value=z.string().max(2000).refine(s=>!/[\r\n\0']/g.test(s),'Use a single-line value without quotes.');
export function registerIntegrations(app,env,options={}){
 const checks={};
 const summary=()=>({email:{host:env.SMTP_HOST||'',port:Number(env.SMTP_PORT||587),secure:env.SMTP_SECURE==='true',user:env.SMTP_USER||'',from:env.SMTP_FROM||'',hasPassword:!!env.SMTP_PASSWORD,configured:!!(env.SMTP_HOST&&env.SMTP_FROM),check:checks.email||null},whatsapp:{provider:env.EVOLUTION_API_URL?'evolution':'openwa',url:env.EVOLUTION_API_URL||env.OPENWA_BASE_URL||'',session:env.EVOLUTION_INSTANCE||env.OPENWA_SESSION_ID||'',hasKey:!!(env.EVOLUTION_API_KEY||env.OPENWA_API_KEY),configured:!!((env.EVOLUTION_API_URL&&env.EVOLUTION_API_KEY&&env.EVOLUTION_INSTANCE)||(env.OPENWA_BASE_URL&&env.OPENWA_API_KEY&&env.OPENWA_SESSION_ID)),check:checks.whatsapp||null}});
 const persist=async patch=>{await(options.saveConfig||saveEnvPatch)(patch);Object.assign(env,patch)};
 const handle=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){res.status(e instanceof z.ZodError?400:502).json({error:e instanceof z.ZodError?e.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; '):'Connection or configuration could not be completed. Check your provider settings and try again.'})}};
 app.get('/api/integrations',(_req,res)=>res.json(summary()));
 app.put('/api/integrations/email',handle(async(req,res)=>{const b=z.object({host:z.string().trim().regex(/^[a-zA-Z0-9.-]+$/),port:z.number().int().min(1).max(65535),secure:z.boolean(),user:value,password:value,from:z.email()}).parse(req.body);const patch={SMTP_HOST:b.host,SMTP_PORT:String(b.port),SMTP_SECURE:String(b.secure),SMTP_USER:b.user,SMTP_FROM:b.from};if(b.password)patch.SMTP_PASSWORD=b.host==='smtp.gmail.com'?b.password.replace(/\s/g,''):b.password;await persist(patch);checks.email=null;res.json(summary())}));
 app.put('/api/integrations/whatsapp',handle(async(req,res)=>{const b=z.object({provider:z.enum(['openwa','evolution']),url:z.url(),session:value.pipe(z.string().min(1)),key:value}).parse(req.body);const url=new URL(b.url);if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.search||url.hash)throw new z.ZodError([{code:'custom',path:['url'],message:'Use the gateway HTTP(S) base URL without credentials or query parameters.'}]);const evo=b.provider==='evolution';const oldKey=evo?env.EVOLUTION_API_KEY:env.OPENWA_API_KEY;const key=b.key||oldKey;if(!key)throw new z.ZodError([{code:'custom',path:['key'],message:'Enter your gateway API key.'}]);const patch={EVOLUTION_API_URL:evo?b.url.replace(/\/$/,''):'',EVOLUTION_INSTANCE:evo?b.session:'',EVOLUTION_API_KEY:evo?key:'',OPENWA_BASE_URL:evo?'':b.url.replace(/\/$/,''),OPENWA_SESSION_ID:evo?'':b.session,OPENWA_API_KEY:evo?'':key};await persist(patch);checks.whatsapp=null;res.json(summary())}));
 app.post('/api/integrations/email/check',handle(async(_req,res)=>{if(!summary().email.configured)return res.status(400).json({error:'Save your email settings first.'});const transport=(options.createTransport||nodemailer.createTransport)({host:env.SMTP_HOST,port:Number(env.SMTP_PORT||587),secure:env.SMTP_SECURE==='true',auth:env.SMTP_USER?{user:env.SMTP_USER,pass:env.SMTP_PASSWORD}:undefined,connectionTimeout:10000,greetingTimeout:10000,socketTimeout:10000});try{await transport.verify();checks.email={connected:true,checkedAt:new Date().toISOString()};res.json({message:'Email connection verified. No test message was sent.',...checks.email})}finally{transport.close()}}));
 app.post('/api/integrations/whatsapp/check',handle(async(_req,res)=>{const s=summary().whatsapp;if(!s.configured)return res.status(400).json({error:'Save your gateway URL, API key and session first.'});const evo=s.provider==='evolution';const response=await(options.fetch||fetch)(evo?`${s.url}/instance/connectionState/${encodeURIComponent(s.session)}`:`${s.url}/api/sessions/${encodeURIComponent(s.session)}`,{headers:evo?{apikey:env.EVOLUTION_API_KEY}:{'X-API-Key':env.OPENWA_API_KEY},signal:AbortSignal.timeout(10000),redirect:'error'});if(!response.ok)throw Error('Provider rejected connection check');const body=await response.json();const state=evo?body.instance?.state:body.status||body.state;const connected=evo?state==='open':state==='ready'||state==='connected';checks.whatsapp={connected,checkedAt:new Date().toISOString()};res.json({...checks.whatsapp,message:connected?'WhatsApp session is connected.': 'Gateway reached. Link your sender number by scanning the QR code in your gateway dashboard.'})}));
}
