import {useEffect,useState,type FormEvent} from 'react';
import {Heart,ArrowRight,LockKey,Leaf,Eye,EyeSlash} from '@phosphor-icons/react';
import {api} from './api';
type Setup={needsSetup:boolean;registrationOpen:boolean;localSetupAllowed:boolean};
export default function Auth({onLogin,onDemo}:{onLogin:()=>Promise<void>;onDemo:()=>void}){
 const [register,setRegister]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[setup,setSetup]=useState<Setup|null>(null),[showPassword,setShowPassword]=useState(false);
 useEffect(()=>{let active=true;api('/setup').then(value=>{if(active){setSetup(value);setRegister(value.needsSetup)}}).catch(()=>{if(active)setError('We couldn’t connect to Together. Check that the app server is running, then refresh this page.')});return()=>{active=false}},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const fields=Object.fromEntries(new FormData(e.currentTarget));try{await api(register?'/register':'/login',fields);await onLogin()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const first=setup?.needsSetup,needsCode=register&&!(first&&setup?.localSetupAllowed);
 return <main className="auth"><section className="auth-story"><a className="brand" href="#"><span className="brand-mark"><Heart size={24} weight="fill"/></span>together<span className="brand-dot">.</span></a><div><div className="eyebrow"><Leaf size={16}/> A LITTLE CLOSER, EVERY DAY</div><h1>Good conversations.<br/>A stronger <em>us.</em></h1><p>A private little space to make room for each other. Share what’s on your mind, find the right moment, and build a life you both love.</p><div className="auth-quote">“We don’t need to have it all figured out.<br/>We just need to figure it out together.”</div></div><span className="quiet"><LockKey size={15}/> Just the two of you. Always.</span></section><section className="auth-form"><div className="auth-form-inner"><span className="eyebrow">YOUR SHARED SPACE</span><h2>{register?(first?'Your story starts here.':'Join your partner.'):'Welcome back.'}</h2><p>{register?(first?'Create the first account. Then invite your partner from Settings.':'Create your own login for the space your partner started.'):'Sign in with the email and password you registered with.'}</p>{register&&first&&setup?.localSetupAllowed&&<div className="info-box"><LockKey size={19}/><p>You’re creating this private space on your computer. No invitation code needed.</p></div>}
 <form onSubmit={submit}>{register&&<label htmlFor="auth-name">Your name<input id="auth-name" name="name" autoComplete="given-name" required maxLength={80}/></label>}<label htmlFor="auth-email">Email address<input id="auth-email" name="email" type="email" autoComplete="email" required/></label><label htmlFor="auth-password">Password</label><div className="password-control"><input id="auth-password" name="password" type={showPassword?'text':'password'} minLength={register?12:undefined} maxLength={200} autoComplete={register?'new-password':'current-password'} aria-describedby={register?'password-help':undefined} required/><button type="button" aria-label={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeSlash size={20}/>:<Eye size={20}/>}</button></div>{register&&<small className="field-help" id="password-help">Use at least 12 characters. A memorable phrase works well.</small>}
 {register&&<><label htmlFor="auth-whatsapp">WhatsApp number<input id="auth-whatsapp" name="whatsapp" type="tel" placeholder="+91 98765 43210" autoComplete="tel" required/><small>Include your country code. Spaces are fine.</small></label>{needsCode&&<label htmlFor="auth-invite">{first?'Private setup code':'Partner invite code'}<input id="auth-invite" name="inviteCode" required autoComplete="off"/><small>{first?'This hosted installation is protected. Use the setup code configured by your host.':'Your partner signs in, opens Settings, and selects “Get partner invite code”.'}</small></label>}<label className="check-label"><input type="checkbox" required/> I agree to receive private discussion and scheduling alerts.</label></>}
 {error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy||!setup}>{busy?'One moment…':register?'Create my account':'Sign in'}<ArrowRight size={18}/></button></form>
 {(register||setup?.registrationOpen)&&<p className="auth-switch">{register?'Already have an account?':first?'Ready to begin?':'Joining your partner?'} <button className="text-button" onClick={()=>{setRegister(!register);setError('')}}>{register?'Sign in':'Create an account'}</button></p>}{!register&&setup&&!setup.registrationOpen&&<p className="quiet centered">Both accounts are registered. Sign in to your existing account.</p>}
 <div className="auth-divider"><span>or take a look around</span></div><button className="button secondary full" onClick={onDemo}>Explore the interactive demo <ArrowRight size={17}/></button><small className="demo-explain">Sample data only. No messages are sent.</small></div></section></main>
}
