import {useEffect,useState,type FormEvent} from 'react';
import {Envelope,WhatsappLogo,CalendarBlank,Check,LockKey} from '@phosphor-icons/react';
import {api} from './api';
type Config={email:{host:string;port:number;secure:boolean;user:string;from:string;hasPassword:boolean;configured:boolean};whatsapp:{provider:string;url:string;session:string;hasKey:boolean;configured:boolean}};
export function Connections({demo}:{demo:boolean}){
 const [config,setConfig]=useState<Config|null>(null),[editing,setEditing]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=()=>api('/integrations').then(setConfig);
 useEffect(()=>{if(!demo)load().catch(e=>setError(e.message))},[demo]);
 async function check(channel:string){setBusy(true);setError('');setMessage('');try{const r=await api(`/integrations/${channel}/check`,{});setMessage(r.message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(e:FormEvent<HTMLFormElement>,channel:string){e.preventDefault();setBusy(true);setError('');setMessage('');const f=new FormData(e.currentTarget);const body=channel==='email'?{host:f.get('host'),port:Number(f.get('port')),secure:f.get('secure')==='on',user:f.get('user'),from:f.get('from'),password:f.get('password')}:{provider:f.get('provider'),url:f.get('url'),session:f.get('session'),key:f.get('key')};try{setConfig(await api('/integrations/'+channel,body,'PUT'));setEditing('');setMessage('Settings saved privately. Use Check connection to verify them.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel settings-card"><WhatsappLogo size={28}/><h2>Stay gently connected</h2>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="info-box" role="status">{message}</p>}
 <div className="integration-row"><Envelope size={22}/><div><strong>Email notifications</strong><p>{config?.email.configured?config.email.from:'Connect your sender account'}</p></div><span className={'status '+(config?.email.configured?'scheduled':'pending')}>{config?.email.configured?'Configured':'Setup needed'}</span></div>
 <div className="connection-actions"><button className="button secondary" disabled={demo||busy} onClick={()=>setEditing(editing==='email'?'':'email')}>Set up email</button><button className="text-button" disabled={demo||busy||!config?.email.configured} onClick={()=>check('email')}>Check connection <Check size={15}/></button></div>
 {editing==='email'&&config&&<form className="connection-form" onSubmit={e=>save(e,'email')}><div className="info-box"><LockKey size={18}/><p>For Gmail, use smtp.gmail.com, port 465, TLS enabled, and a Google app password.</p></div><label>SMTP host<input name="host" defaultValue={config.email.host||'smtp.gmail.com'} required/></label><div className="form-grid"><label>Port<input name="port" type="number" defaultValue={config.email.host?config.email.port:465} required min="1" max="65535"/></label><label className="check-label"><input name="secure" type="checkbox" defaultChecked={config.email.host?config.email.secure:true}/>TLS (port 465)</label></div><label>Sender email<input name="from" type="email" defaultValue={config.email.from} required/></label><label>SMTP username<input name="user" defaultValue={config.email.user} required autoComplete="off"/></label><label>App password<input name="password" type="password" autoComplete="new-password" required={!config.email.hasPassword} placeholder={config.email.hasPassword?'Saved securely; leave blank to keep it':'Your provider app password'}/></label><button className="button primary full" disabled={busy}>Save email settings</button></form>}
 <div className="integration-row"><CalendarBlank size={22}/><div><strong>Google Calendar invitations</strong><p>{config?.email.configured?'Enabled through your email sender':'Connect email to enable invitations'}</p></div><span className={'status '+(config?.email.configured?'scheduled':'pending')}>{config?.email.configured?'Ready':'Needs email'}</span></div><p className="quiet">When a conversation is scheduled, both of you receive an invitation. Accept it in Gmail or Google Calendar. Calendar responses stay in Google; they aren’t synced back here.</p>
 <div className="integration-row"><WhatsappLogo size={22}/><div><strong>WhatsApp · {config?.whatsapp.provider==='evolution'?'Evolution':'OpenWA'}</strong><p>{config?.whatsapp.configured?'Gateway credentials saved':'Connect a gateway and link a sender number'}</p></div><span className={'status '+(config?.whatsapp.configured?'scheduled':'pending')}>{config?.whatsapp.configured?'Configured':'Setup needed'}</span></div>
 <div className="connection-actions"><button className="button secondary" disabled={demo||busy} onClick={()=>setEditing(editing==='whatsapp'?'':'whatsapp')}>Set up WhatsApp</button><button className="text-button" disabled={demo||busy||!config?.whatsapp.configured} onClick={()=>check('whatsapp')}>Check connection <Check size={15}/></button></div>
 {editing==='whatsapp'&&config&&<form className="connection-form" onSubmit={e=>save(e,'whatsapp')}><p className="quiet">Start your gateway, then scan its WhatsApp QR code with the sender phone. Enter its connection details below.</p><label>Gateway<select name="provider" defaultValue={config.whatsapp.provider}><option value="openwa">OpenWA</option><option value="evolution">Evolution API</option></select></label><label>Gateway base URL<input name="url" type="url" defaultValue={config.whatsapp.url} placeholder="http://127.0.0.1:2785" required/></label><label>Session ID / instance name<input name="session" defaultValue={config.whatsapp.session} required/></label><label>Gateway API key<input name="key" type="password" autoComplete="new-password" required={!config.whatsapp.hasKey} placeholder={config.whatsapp.hasKey?'Saved securely; leave blank to keep it':'From your gateway dashboard'}/></label><button className="button primary full" disabled={busy}>Save WhatsApp settings</button></form>}
 <div className="info-box"><LockKey size={18}/><p>{demo?'Connection settings are disabled in the demo.':'Credentials stay on the server and are never returned to your browser. Connection checks do not send messages.'}</p></div></section>
}
